## path
data_path: ../data/dailydialog/test.jsonl
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: null
src: context
trg: response
## training
per_device_eval_batch_size: 12
accelerator: gpu
train_max_src_len: 120
train_max_trg_len: 55
seed: 980406
## generation
gen_max_len: 58
gen_min_len: 5
num_beams: 5