## path
data_path: ../data/xsum/test.jsonl
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: null
default_root_dir: /tmp
src: document
trg: summary
## training
per_device_eval_batch_size: 8
accelerator: gpu
train_max_src_len: 512
train_max_trg_len: 80
seed: 980406
## generation
gen_max_len: 64
length_penalty: 0.6
num_beams: 32
num_return_sequences: 16
early_stopping: true
no_repeat_ngram_size: 3