# data
data_dir: ../data/xsum
candidate_dir: null
pretrained_model_path: ../pretrained_model/robert_base
src: document
trg: summary
accelerator: gpu
num_candidates: 16
candidates_sampling: sequential
max_src_len: 512
max_trg_len: 80
## reranker
architecture: dual_tower
## contrastive
contrastive_loss: false
temperature: 0.05
## simcls_loss
simcls_loss: false
margin: 0.01
no_gold: false
gold_weight: 1.0
gold_margin: 0.0
## training
lr: 2.0e-3
warmup_steps: 10000
per_device_train_batch_size: 12
per_device_eval_batch_size: 8
logging_steps: 100
eval_metrics: rouge1
seed: 980406
accumulate_grad_batches: 1
max_epochs: 5