## path
data_path: ../data/jrc_deen/test.jsonl
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: null
src: src
trg: trg
## training
per_device_eval_batch_size: 32
accelerator: gpu
train_max_src_len: 250
train_max_trg_len: 130
seed: 980406
## generation
gen_max_len: 118
gen_min_len: 3
num_beams: 5