## path
data_dir: ../data/jrc_enes
pretrained_model_path: ../pretrained_model/transformer_base_jrc_enes
default_root_dir: null
memory_dir: null
memory_encoding: concate
src: src
trg: trg
## training
per_device_train_batch_size: 48
accumulate_grad_batches: 1
per_device_eval_batch_size: 48
lr: 4.4e-2
warmup_steps: 4000
accelerator: gpu
max_epochs: 30
val_check_interval: 1.0
label_smoothing_factor: 0.1
gradient_clip_val: 1.0 
train_max_src_len: 350
train_max_trg_len: 130
logging_steps: 100
eval_metrics: bleu
seed: 980406
## generation
gen_max_len: 118
gen_min_len: 3
num_beams: 5

